binop_separator = "front"
comment_width = 80
condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_single_line = true
format_strings = true
match_arm_blocks = true
max_width = 80
normalize_comments = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
#same_line_attributes = true
spaces_around_ranges = true
#struct_field_align_threshold = 10
trailing_semicolon = false
use_small_heuristics = true
use_try_shorthand = true
wrap_comments = true
